name: StoneStatue
version: ${project.version}
main: cn.smallairplane.mc.stonestatue.StoneStatue
api-version: 1.16
authors: [ Hang_456 ]
description: 登录插件
website: mc.smallairplane.cn
commands:
  login:
    aliases:
      - "log"
    description: "登录命令"
    usage: "/login <密码>"
  register:
    aliases:
      - "reg"
    description: "注册账号"
    usage: "/register <密码> <确认密码>"
